### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by sequent** [jaumebonet/RGcrawler#1]
I am interested in your program, but I have a problem use. You use the library "librarian" and I do not find it in the available repositories.

**Comment by jaumebonet** [comment]
Hi!
RGcrawler is a bit old. I've been trying to make it work for the last couple of weeks, but so much things have changed, both in my code and in ResearchGate's markup.
The library is currently this one: [pynion](https://bitbucket.org/jaumebonet/pynion), but it would need a bit more than simple changing the import name.
I'm in the process of fixing it all, but, to be honest, I doubt I'll have the time to actually make it work until Christmas.
As soon as I fix it, I'll post it here.
Thanks four your interest,
Jaume.-

**Comment by sequent** [comment]
Thanks for the quick response. I also collect data from different scientific sources (Scholar, MSAcademy), but faced with the complexity of collecting data from RS. I will follow the changes in your repository.

**Comment by jaumebonet** [comment]
Hi!
I just updated the library with a small usage explanation.
This is as far as I will go right now, as it covers my current needs and I have little time left.
Don't hesitate to ask if something is not clear.
I hope that it helps!
J.-
